export const NS = {
  PET_STORE: {
    LIST_PETS: "PET_STORE.LIST_PETS",
    CREATE_PET: "CREATE_PET.CREATE_PET",
    GET_PET: "PET_STORE.GET_PET",
  },
  GITHUB: {
    LIST_REPOS: "GITHUB.LIST_REPOS",
  },
  GLOBAL: {
    LOGIN: "GLOBAL.LOGIN",
    LOGOUT: "GLOBAL.LOGOUT",
  },
};
